apiVersion: v1
kind: Service
metadata:
  name: hello-api
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hello-api
    app.kubernetes.io/instance: hello-api
