apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-api
      app.kubernetes.io/instance: hello-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-api
        app.kubernetes.io/instance: hello-api
    spec:
      securityContext:
        {}
      containers:
        - name: hello-api
          image: "localhost:5000/hello-api:crac-1"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"          
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          #command: ["java","-jar","/app/hello-api.jar"]
          command: ["java"]
          args: ["-XX:CRaCRestoreFrom=./crac"]
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 1
          securityContext:
            privileged: true
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
