/**
 * Hello API
 *
 * Contact: pbousquet@sqli.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiErrorResponse } from '../model/models';
import { HelloDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HelloServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Saluer une personne en particulier
     * Retourne un message de salutation personalisé.
     * @param name Nom de la personne à saluer
     */
    helloWithName(name: string, extraHttpRequestParams?: any): Observable<HelloDto>;

    /**
     * Saluer le monde
     * Retourne un message de salutation générique.
     */
    helloWorld(extraHttpRequestParams?: any): Observable<HelloDto>;

}
