/**
 * Hello API
 * Hello API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pbousquet@sqli.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiErrorResponse { 
    timestamp?: string;
    status?: number;
    error?: string;
    message?: string;
    path?: string;
}

